# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('content', models.TextField(null=True, verbose_name='Content')),
                ('likes', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
